version: "3.1"

services:
  db:
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 451ws380lc++A
      POSTGRES_USER: root
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data:
    external: true
